import { useEffect } from "react";
import { useLocation, Link } from "wouter";
import { scrollTop } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Calculator, Shield, ArrowRight, ChevronRight,
  BarChart3, Lock,
  FileText, TrendingUp, Activity,
  Check, Scale
} from "lucide-react";
import { EXAMPLE_SCENARIOS } from "@/lib/exampleScenarios";
import { useAppStore } from "@/hooks/use-store";
import { useDocumentTitle } from "@/hooks/use-document-title";
import { useMetaTags } from "@/hooks/use-meta-tags";
import { Logo } from "@/components/logo";

const WHAT_YOU_GET = [
  "Net property equity and transaction cost modelling",
  "Liquid assets, liabilities, and pension allocation analysis",
  "UK 2025/26 income tax and National Insurance modelling",
  "Indicative lending capacity benchmarks (non-lender specific)",
  "Capital allocation and liquidity concentration analysis",
  "5-year capital sustainability projections",
  "Interest rate and expense sensitivity testing",
  "Downloadable Structured Financial Brief (PDF)",
];

const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Enter Your Financial Assumptions",
    body: "Privately, in your own time, with no pressure to share.",
    icon: Calculator,
  },
  {
    step: 2,
    title: "Model Settlement Structures",
    body: "Compare selling, retaining the home, and adjusted splits.",
    icon: BarChart3,
  },
  {
    step: 3,
    title: "Compare Stability & Sustainability",
    body: "Understand what drives each outcome, not just the headline totals.",
    icon: Activity,
  },
  {
    step: 4,
    title: "Generate a Financial Brief",
    body: "A clear overview to inform professional conversations.",
    icon: FileText,
  },
];

const FAQ_ITEMS_LANDING = [
  {
    q: "Does this predict what I will receive in court?",
    a: "No. This tool does not predict court outcomes, judicial discretion, legal entitlement, or settlement fairness. It models financial structures only. A court considers a wide range of factors — including needs, contributions, and welfare of children — that are beyond the scope of any mathematical model.",
  },
  {
    q: "Is this financial or legal advice?",
    a: "No. This tool provides illustrative financial modelling only. It is not authorised or regulated by the FCA, SRA, or any other professional body. Independent professional advice may be warranted before making any decisions.",
  },
  {
    q: "How accurate are the tax calculations?",
    a: "The tax engine applies a simplified UK income tax and employee Class 1 National Insurance calculation only, based on published HMRC 2025/26 rates. It excludes dividend rates, Scottish rates, self-employed NI, Capital Gains Tax, pension relief, and other reliefs. Full details are available on the Model Methodology page.",
  },
  {
    q: "What do the lending capacity benchmarks mean?",
    a: "These are generalised income multiple illustrations (typically 4-4.5x gross income) and do not constitute a lending assessment, mortgage advice, or credit approval indication. Actual lending decisions depend on individual creditworthiness, lender criteria, and other factors.",
  },
  {
    q: "Is my data safe?",
    a: "All financial calculations are performed locally in your web browser. The financial data you enter is not transmitted to our servers. Payment processing is handled securely by Stripe.",
  },
  {
    q: "What are the scope and limitations of this tool?",
    a: "This platform provides illustrative financial modelling only. It does not provide legal, financial, or tax advice. It does not predict court outcomes, assess entitlement, provide suitability assessments or lending evaluations, or replace independent professional advice. All outputs are generated solely from the financial assumptions entered by the user.",
  },
  {
    q: "What does the Financial Sustainability Indicator mean?",
    a: "This is a model-based indicator generated by a simplified mathematical model. It reflects liquidity sustainability and lending capacity benchmarks under current modelling assumptions. It does not constitute financial advice, risk profiling, or suitability assessment.",
  },
];

function useLandingFaqJsonLd(faqItems: { q: string; a: string }[]) {
  useEffect(() => {
    const script = document.createElement("script");
    script.type = "application/ld+json";
    const faqData = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": faqItems.map((item) => ({
        "@type": "Question",
        "name": item.q,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": item.a,
        },
      })),
    };
    script.textContent = JSON.stringify(faqData);
    document.head.appendChild(script);
    return () => {
      if (script.parentNode) script.parentNode.removeChild(script);
    };
  }, [faqItems]);
}

const ANALYSIS_PREVIEW_FEATURES = [
  {
    icon: BarChart3,
    title: "Scenario Comparison",
    body: "See how selling, one party keeping the home, and deferred sale compare side-by-side across net positions and monthly costs.",
  },
  {
    icon: Activity,
    title: "Financial Sustainability Indicator",
    body: "A model-based score that illustrates how sustainable each party's post-settlement finances look over a 5-year horizon.",
  },
  {
    icon: TrendingUp,
    title: "5-Year Capital Projection",
    body: "Projects how liquid capital may change over time under each scenario, accounting for income, expenses, and mortgage payments.",
  },
];

export default function LandingPage() {
  useDocumentTitle("Divorce Calculator UK (2026) | Financial Settlement Tool");
  useMetaTags({
    description: "Estimate your UK divorce settlement with a structured financial modelling tool. Compare scenarios, assess sustainability, and understand long-term financial outcomes. UK 2025/26 tax rules.",
    canonical: "https://divorcecalculatoruk.co.uk/",
    ogTitle: "Divorce Calculator UK (2026) | Financial Settlement Tool",
    ogDescription: "Model different divorce financial settlement scenarios with UK 2025/26 tax rules applied. Compare sell vs retain options and understand long-term outcomes.",
  });
  useLandingFaqJsonLd(FAQ_ITEMS_LANDING);
  const [, setLocation] = useLocation();
  const loadState = useAppStore((s) => s.loadState);
  const reset = useAppStore((s) => s.reset);

  const startFresh = () => {
    scrollTop();
    reset();
    setLocation("/wizard");
  };

  const loadExample = (index: number) => {
    const example = EXAMPLE_SCENARIOS[index];
    loadState(example.data);
    setLocation("/preview");
  };

  return (
    <div className="min-h-screen bg-background font-sans">
      <div className="bg-primary/10 text-primary px-4 py-1.5 text-xs text-center font-medium border-b border-primary/20" data-testid="text-disclaimer">
        Illustrative modelling only. Not legal, tax or financial advice.
      </div>

      <nav className="sticky top-0 z-[100] w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto px-4 h-12 flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-4">
            <Logo href="/" size="sm" showBrandName />
            <Link href="/methodology" onClick={scrollTop} className="text-sm text-muted-foreground hover:text-foreground transition-colors hidden sm:inline" data-testid="link-nav-methodology">Methodology</Link>
            <Link href="/divorce-financial-modelling" onClick={scrollTop} className="text-sm text-muted-foreground hover:text-foreground transition-colors hidden sm:inline" data-testid="link-nav-guides">Guides</Link>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                scrollTop();
                setLocation("/unlock");
              }}
              data-testid="button-nav-buy-now"
            >
              Buy Now
            </Button>
            <Button
              onClick={startFresh}
              data-testid="button-nav-start"
            >
              Start Now <ArrowRight className="w-4 h-4 ml-1" />
            </Button>
          </div>
        </div>
      </nav>

      <section className="relative overflow-hidden bg-primary" data-testid="section-hero">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_hsl(220_60%_35%),_transparent_60%)] pointer-events-none" />
        <div className="container mx-auto px-4 pt-16 pb-20 md:pt-24 md:pb-28 relative">
          <div className="grid gap-12 lg:grid-cols-2 lg:gap-16 items-center max-w-6xl mx-auto">
            <div className="space-y-6 text-center lg:text-left">
              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2">
                <Badge variant="outline" className="text-xs px-3 py-1 border-gold/50 text-gold bg-gold/10">
                  UK 2025/26 Tax &amp; NI Rates
                </Badge>
              </div>
              <h1 className="text-4xl md:text-5xl font-display font-bold leading-tight text-white" data-testid="text-hero-headline">
                Divorce Calculator UK — Understand your financial position before spending thousands on legal fees.
              </h1>
              <p className="text-lg text-white/70 leading-relaxed">
                Model different divorce financial settlement scenarios with UK 2025/26 tax and National Insurance rates applied. Understand the long-term financial outcomes of each option — not just the numbers, but what they mean for your future.
              </p>
              <p className="text-sm text-white/45">
                Illustrative modelling only. Not legal, tax, or financial advice.
              </p>
              <div className="flex flex-col items-center lg:items-start justify-center lg:justify-start gap-3 pt-1">
                <div className="flex flex-col gap-2 items-center lg:items-start w-full sm:w-auto">
                  <Button
                    size="lg"
                    onClick={startFresh}
                    data-testid="button-hero-start"
                    className="bg-gold hover:bg-gold/90 text-white border-0 shadow-lg shadow-gold/25 w-full sm:w-auto"
                  >
                    Start My Financial Model <ArrowRight className="w-4 h-4 ml-1.5" />
                  </Button>
                  <Button
                    size="lg"
                    onClick={() => {
                      scrollTop();
                      setLocation("/unlock");
                    }}
                    data-testid="button-hero-buy-now"
                    className="bg-gold hover:bg-gold/90 text-white border-0 shadow-lg shadow-gold/25 w-full sm:w-auto"
                  >
                    Buy Now — £79 <ArrowRight className="w-4 h-4 ml-1.5" />
                  </Button>
                  <p className="text-xs text-white/45">One-time payment. No subscription.</p>
                </div>
                <div className="flex flex-col sm:flex-row gap-2 w-full sm:w-auto justify-center lg:justify-start">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => loadExample(0)}
                    data-testid="button-hero-example"
                    className="border-white/25 text-white hover:bg-white/10 hover:text-white bg-transparent"
                  >
                    View Example <ChevronRight className="w-3.5 h-3.5 ml-1" />
                  </Button>
                </div>
              </div>
              <div className="flex items-center gap-3 text-xs text-white/45">
                <span>Private. Structured. No sign-up required.</span>
                <span>·</span>
                <Link href="/free-guide" onClick={scrollTop} className="underline underline-offset-2 text-white/55 hover:text-white transition-colors" data-testid="link-hero-free-guide">
                  Free guide →
                </Link>
              </div>
            </div>

            <div className="relative" data-testid="div-dashboard-mockup">
              <div className="rounded-xl border border-white/15 bg-background shadow-2xl overflow-hidden ring-1 ring-white/10">
                <div className="bg-primary/8 border-b border-border/40 px-4 py-2.5 flex items-center gap-2">
                  <div className="h-2.5 w-2.5 rounded-full bg-red-400/70" />
                  <div className="h-2.5 w-2.5 rounded-full bg-amber-400/70" />
                  <div className="h-2.5 w-2.5 rounded-full bg-green-400/70" />
                  <span className="text-[10px] text-muted-foreground ml-2 font-mono">Settlement Analysis — Example</span>
                </div>
                <div className="p-4 space-y-4">
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2">Financial Sustainability Indicator</p>
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between gap-3">
                        <span className="text-xs text-muted-foreground w-28 truncate">Sell &amp; Split</span>
                        <div className="flex-1 bg-muted rounded-full h-1.5">
                          <div className="bg-green-500 h-1.5 rounded-full" style={{width: "82%"}} />
                        </div>
                        <span className="text-xs font-semibold text-green-600 w-20 text-right">82 · Higher</span>
                      </div>
                      <div className="flex items-center justify-between gap-3">
                        <span className="text-xs text-muted-foreground w-28 truncate">A Retains Home</span>
                        <div className="flex-1 bg-muted rounded-full h-1.5">
                          <div className="bg-amber-500 h-1.5 rounded-full" style={{width: "67%"}} />
                        </div>
                        <span className="text-xs font-semibold text-amber-600 w-20 text-right">67 · Moderate</span>
                      </div>
                      <div className="flex items-center justify-between gap-3">
                        <span className="text-xs text-muted-foreground w-28 truncate">B Retains Home</span>
                        <div className="flex-1 bg-muted rounded-full h-1.5">
                          <div className="bg-red-500 h-1.5 rounded-full" style={{width: "38%"}} />
                        </div>
                        <span className="text-xs font-semibold text-red-600 w-20 text-right">38 · Lower</span>
                      </div>
                    </div>
                  </div>
                  <div className="border-t border-border/40 pt-3">
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2">Allocated Net Position</p>
                    <div className="space-y-2">
                      {[
                        { label: "Sell & Split", a: 72, b: 68 },
                        { label: "A Retains", a: 45, b: 88 },
                        { label: "B Retains", a: 91, b: 31 },
                      ].map(({ label, a, b }) => (
                        <div key={label}>
                          <div className="flex justify-between mb-0.5">
                            <span className="text-[10px] text-muted-foreground">{label}</span>
                          </div>
                          <div className="flex gap-1 h-4">
                            <div className="bg-primary rounded-sm" style={{ width: `${a}%` }} title="Party A" />
                            <div className="bg-teal-500 rounded-sm" style={{ width: `${b}%` }} title="Party B" />
                          </div>
                        </div>
                      ))}
                      <div className="flex items-center gap-3 pt-1">
                        <div className="flex items-center gap-1"><div className="h-2 w-4 bg-primary rounded-sm" /><span className="text-[10px] text-muted-foreground">You</span></div>
                        <div className="flex items-center gap-1"><div className="h-2 w-4 bg-teal-500 rounded-sm" /><span className="text-[10px] text-muted-foreground">Other party</span></div>
                      </div>
                    </div>
                  </div>
                  <div className="border-t border-border/40 pt-3">
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2">5-Year Capital Projection</p>
                    <svg viewBox="0 0 220 50" className="w-full h-12" fill="none">
                      <polyline points="0,40 40,32 80,22 120,18 160,14 220,10" stroke="hsl(var(--primary))" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
                      <polyline points="0,44 40,42 80,40 120,44 160,48 220,46" stroke="#14b8a6" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="4 2" />
                    </svg>
                  </div>
                </div>
                <div className="border-t border-border/30 bg-muted/30 px-4 py-2">
                  <p className="text-[10px] text-muted-foreground/60 text-center">Example output — illustrative figures only</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 md:py-20 bg-background" data-testid="section-features">
        <div className="container mx-auto px-4">
          <div className="max-w-5xl mx-auto">
            <div className="grid gap-12 lg:gap-16 lg:grid-cols-2">
              <div className="space-y-5">
                <h2 className="text-2xl md:text-3xl font-display font-bold" data-testid="text-quantifies-headline">
                  What This Model Quantifies
                </h2>
                <ul className="space-y-2.5">
                  {WHAT_YOU_GET.map((item, i) => (
                    <li key={i} className="flex items-start gap-2.5" data-testid={`text-feature-${i}`}>
                      <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                      <span className="text-sm leading-snug">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="space-y-5">
                <h2 className="text-2xl md:text-3xl font-display font-bold" data-testid="text-how-headline">
                  How It Works
                </h2>
                <div className="space-y-5">
                  {HOW_IT_WORKS.map((item) => (
                    <div key={item.step} className="flex items-start gap-4" data-testid={`step-how-${item.step}`}>
                      <div className="h-10 w-10 rounded-md bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold shrink-0">
                        {item.step}
                      </div>
                      <div>
                        <h3 className="text-sm font-semibold">{item.title}</h3>
                        <p className="text-xs text-muted-foreground leading-relaxed mt-0.5">{item.body}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 md:py-20" data-testid="section-analysis-preview">
        <div className="container mx-auto px-4">
          <div className="text-center mb-10 max-w-xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-display font-bold" data-testid="text-analysis-preview-headline">
              What Your Analysis Includes
            </h2>
            <p className="text-sm text-muted-foreground mt-3">
              Every model includes structured outputs across three core areas. All included in the full analysis.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-3 max-w-4xl mx-auto">
            {ANALYSIS_PREVIEW_FEATURES.map((feature, i) => (
              <Card key={i} data-testid={`card-analysis-feature-${i}`} className="shadow-sm hover:shadow-md transition-shadow border-border/60">
                <CardContent className="pt-5 pb-5 space-y-3">
                  <div className="h-9 w-9 rounded-md bg-primary/10 flex items-center justify-center">
                    <feature.icon className="w-4.5 h-4.5 text-primary" />
                  </div>
                  <h3 className="text-sm font-semibold">{feature.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{feature.body}</p>
                  <Badge variant="outline" className="text-[10px] px-1.5 py-0 text-gold border-gold/40 bg-gold/5">
                    Included in full analysis
                  </Badge>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 md:py-20 bg-primary/6 border-y border-primary/15" data-testid="section-fsi-callout">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto grid gap-10 lg:grid-cols-2 items-center">
            <div className="space-y-4">
              <Badge className="text-xs px-3 py-1 bg-primary/10 text-primary border-primary/20" variant="outline">
                Unique to this tool
              </Badge>
              <h2 className="text-2xl md:text-3xl font-display font-bold" data-testid="text-fsi-headline">
                The UK divorce tool that scores your financial sustainability — not just the numbers
              </h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                Most calculators show you a number. The Financial Sustainability Indicator (FSI) shows you what that number <em>means</em> — scoring how viable each settlement option is for each party based on income, outgoings, housing costs, and capital position over a 5-year horizon.
              </p>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Scored 0–100. Green is sustainable. Amber warrants attention. Red indicates financial stress under current assumptions. Each score comes with plain-English driver explanations.
              </p>
              <Button onClick={startFresh} data-testid="button-fsi-cta" className="bg-gold hover:bg-gold/90 text-white border-0 shadow-md shadow-gold/20">
                See Your Sustainability Score <ArrowRight className="w-4 h-4 ml-1.5" />
              </Button>
            </div>
            <div className="space-y-3">
              {[
                { label: "Sell & Split", score: 82, colour: "bg-green-500", text: "82 — Sustainable" },
                { label: "You Retain Home", score: 67, colour: "bg-amber-500", text: "67 — Monitor closely" },
                { label: "They Retain Home", score: 48, colour: "bg-red-500", text: "48 — Financial stress risk" },
              ].map(row => (
                <div key={row.label} className="p-3 rounded-md bg-background border border-border/50">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-medium">{row.label}</span>
                    <span className="text-xs font-semibold text-muted-foreground">{row.text}</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2">
                    <div className={`${row.colour} h-2 rounded-full transition-all`} style={{ width: `${row.score}%` }} />
                  </div>
                </div>
              ))}
              <p className="text-xs text-muted-foreground/60 text-center pt-1">Illustrative example — your scores will be personalised to your figures</p>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 md:py-20" data-testid="section-examples">
        <div className="container mx-auto px-4">
          <div className="text-center mb-10">
            <h2 className="text-2xl md:text-3xl font-display font-bold" data-testid="text-examples-headline">
              Example Output
            </h2>
            <p className="text-sm text-muted-foreground mt-3 max-w-lg mx-auto">
              Load a sample scenario to explore the full structured analysis. No sign-up required.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 max-w-4xl mx-auto">
            {EXAMPLE_SCENARIOS.map((example, i) => (
              <Card
                key={example.id}
                className="hover-elevate active-elevate-2 cursor-pointer transition-all"
                onClick={() => loadExample(i)}
                data-testid={`card-example-${example.id}`}
              >
                <CardContent className="pt-5 pb-4 space-y-3">
                  <div className="flex items-start justify-between gap-2">
                    <h3 className="text-sm font-semibold text-foreground">{example.title}</h3>
                    <ArrowRight className="w-4 h-4 text-muted-foreground/50 mt-0.5 flex-shrink-0" />
                  </div>
                  <p className="text-xs text-muted-foreground">{example.subtitle}</p>
                  <p className="text-xs text-muted-foreground/80 leading-relaxed">{example.description}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {example.highlights.map((h, hi) => (
                      <Badge key={hi} variant="outline" className="text-[10px] px-1.5 py-0">
                        {h}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 md:py-20 bg-primary" data-testid="section-pricing">
        <div className="container mx-auto px-4 max-w-2xl text-center space-y-6">
          <div className="inline-flex items-center gap-2 bg-gold/15 text-gold border border-gold/30 text-xs font-semibold px-3 py-1 rounded-full mb-2">
            One-time payment · No subscription
          </div>
          <h2 className="text-2xl md:text-3xl font-display font-bold text-white" data-testid="text-pricing-headline">
            Full Structured Analysis &mdash; <span className="text-gold">&pound;79</span>
          </h2>
          <p className="text-white/65 leading-relaxed">
            A single professional consultation could cost <span className="font-semibold text-white">&pound;250&ndash;&pound;400 per hour</span>. This platform provides structured modelling and scenario comparison for a <span className="font-semibold text-gold">one-time &pound;79</span>, with six months of unlimited reruns.
          </p>
          <div className="grid grid-cols-3 gap-4 text-center max-w-md mx-auto py-6 border-y border-white/10">
            <div>
              <p className="text-2xl font-bold text-gold">15 min</p>
              <p className="text-xs text-white/55 mt-1">First model complete</p>
            </div>
            <div>
              <p className="text-2xl font-bold text-gold">6 months</p>
              <p className="text-xs text-white/55 mt-1">Unlimited reruns</p>
            </div>
            <div>
              <p className="text-2xl font-bold text-gold">100%</p>
              <p className="text-xs text-white/55 mt-1">Private &amp; secure</p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
            <Button
              size="lg"
              onClick={startFresh}
              data-testid="button-pricing-start"
              className="bg-gold hover:bg-gold/90 text-white border-0 shadow-lg shadow-gold/25"
            >
              Start My Financial Model <ArrowRight className="w-4 h-4 ml-1.5" />
            </Button>
            <Button
              size="lg"
              variant="outline"
              onClick={() => { scrollTop(); setLocation("/unlock"); }}
              data-testid="button-pricing-buy"
              className="border-white/25 text-white hover:bg-white/10 hover:text-white bg-transparent"
            >
              Buy Now — £79 <ArrowRight className="w-4 h-4 ml-1.5" />
            </Button>
          </div>
          <div className="flex flex-wrap items-center justify-center gap-4 text-xs text-white/40 pt-2">
            <div className="flex items-center gap-1.5">
              <Lock className="w-3.5 h-3.5" />
              <span>All calculations in-browser</span>
            </div>
            <span>&middot;</span>
            <div className="flex items-center gap-1.5">
              <Shield className="w-3.5 h-3.5" />
              <span>No data stored on servers</span>
            </div>
            <span>&middot;</span>
            <div className="flex items-center gap-1.5">
              <TrendingUp className="w-3.5 h-3.5" />
              <span>Stripe-secured payments</span>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 md:py-24 bg-background" data-testid="section-cta">
        <div className="container mx-auto px-4 max-w-lg text-center space-y-6">
          <h2 className="text-3xl md:text-4xl font-display font-bold" data-testid="text-cta-headline">
            Start with structure.
          </h2>
          <p className="text-muted-foreground max-w-md mx-auto leading-relaxed">
            Seeing the numbers clearly, before conversations begin, changes the nature of those conversations entirely.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button
              size="lg"
              onClick={startFresh}
              data-testid="button-cta-start"
              className="bg-gold hover:bg-gold/90 text-white border-0 shadow-lg shadow-gold/25"
            >
              Start My Financial Model <ArrowRight className="w-4 h-4 ml-1.5" />
            </Button>
            <Button
              size="lg"
              variant="outline"
              onClick={() => {
                scrollTop();
                setLocation("/unlock");
              }}
              data-testid="button-cta-buy-now"
            >
              Buy Now <ArrowRight className="w-4 h-4 ml-1.5" />
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Private and secure. All calculations run in your browser.
          </p>
        </div>
      </section>

      <section className="py-16 md:py-20 bg-muted/30" data-testid="section-faq">
        <div className="container mx-auto px-4 max-w-2xl">
          <h2 className="text-2xl md:text-3xl font-display font-bold text-center mb-10" data-testid="text-faq-headline">
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {FAQ_ITEMS_LANDING.map((item, i) => (
              <div key={i} data-testid={`faq-item-${i}`}>
                <h3 className="text-sm font-semibold text-foreground mb-1.5">{item.q}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-14 md:py-16 bg-background border-t border-border/40" data-testid="section-popular-guides">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-xl md:text-2xl font-display font-bold text-center mb-2">Popular Guides</h2>
          <p className="text-sm text-muted-foreground text-center mb-8">Understand the key topics before you model your position.</p>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <Link href="/divorce-financial-settlement-calculator-uk" onClick={scrollTop} data-testid="link-guide-settlement-calc" className="group block p-5 rounded-lg border border-border hover:border-primary/40 hover:shadow-md transition-all bg-background">
              <div className="w-8 h-8 rounded-md bg-primary/8 flex items-center justify-center mb-3 group-hover:bg-primary/12 transition-colors">
                <Scale className="w-4 h-4 text-primary" />
              </div>
              <h3 className="text-sm font-semibold text-foreground mb-1 group-hover:text-primary transition-colors">How Assets Are Divided</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">How UK courts approach divorce financial settlements — and what drives the outcome.</p>
              <span className="inline-flex items-center gap-1 mt-3 text-xs font-medium text-primary">Read guide <ChevronRight className="w-3 h-3" /></span>
            </Link>
            <Link href="/how-much-does-divorce-cost-uk" onClick={scrollTop} data-testid="link-guide-divorce-costs" className="group block p-5 rounded-lg border border-border hover:border-primary/40 hover:shadow-md transition-all bg-background">
              <div className="w-8 h-8 rounded-md bg-primary/8 flex items-center justify-center mb-3 group-hover:bg-primary/12 transition-colors">
                <TrendingUp className="w-4 h-4 text-primary" />
              </div>
              <h3 className="text-sm font-semibold text-foreground mb-1 group-hover:text-primary transition-colors">How Much Does Divorce Cost?</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">A breakdown of typical legal fees, court costs, and financial advice costs in the UK.</p>
              <span className="inline-flex items-center gap-1 mt-3 text-xs font-medium text-primary">Read guide <ChevronRight className="w-3 h-3" /></span>
            </Link>
            <Link href="/who-gets-house-divorce-uk" onClick={scrollTop} data-testid="link-guide-who-gets-house" className="group block p-5 rounded-lg border border-border hover:border-primary/40 hover:shadow-md transition-all bg-background">
              <div className="w-8 h-8 rounded-md bg-primary/8 flex items-center justify-center mb-3 group-hover:bg-primary/12 transition-colors">
                <FileText className="w-4 h-4 text-primary" />
              </div>
              <h3 className="text-sm font-semibold text-foreground mb-1 group-hover:text-primary transition-colors">Who Gets the House?</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">The factors that determine what happens to the family home when a marriage ends.</p>
              <span className="inline-flex items-center gap-1 mt-3 text-xs font-medium text-primary">Read guide <ChevronRight className="w-3 h-3" /></span>
            </Link>
          </div>
        </div>
      </section>

      <footer className="pt-12 pb-8 bg-primary" data-testid="section-footer">
        <div className="container mx-auto px-4 max-w-5xl">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 mb-10">
            <div>
              <Link href="/" onClick={scrollTop} className="inline-block mb-3 group">
                <span className="font-display font-bold text-white text-sm tracking-tight group-hover:text-gold transition-colors">DivorceCalculatorUK</span>
              </Link>
              <p className="text-xs text-white/40 leading-relaxed">
                Illustrative financial modelling for separation and divorce in England &amp; Wales.
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-white/60 uppercase tracking-wider mb-3">Guides &amp; Resources</p>
              <ul className="space-y-2">
                <li><Link href="/free-guide" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-free-guide">Free UK Divorce Guide</Link></li>
                <li><Link href="/divorce-financial-modelling" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-guides">Divorce Financial Modelling</Link></li>
                <li><Link href="/how-much-does-divorce-cost-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-divorce-costs">Divorce Costs UK</Link></li>
                <li><Link href="/divorce-financial-settlement-calculator-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-settlement-calc">Settlement Calculator</Link></li>
                <li><Link href="/divorce-settlement-examples-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-examples">Settlement Examples</Link></li>
              </ul>
            </div>
            <div>
              <p className="text-xs font-semibold text-white/60 uppercase tracking-wider mb-3">Specialist Topics</p>
              <ul className="space-y-2">
                <li><Link href="/divorce-50-50-split-calculator-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-5050">50/50 Split</Link></li>
                <li><Link href="/divorce-house-buyout-calculator-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-house-buyout">House Buyout</Link></li>
                <li><Link href="/divorce-pension-split-calculator-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-pension-split">Pension Split</Link></li>
                <li><Link href="/who-gets-house-divorce-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-who-gets-house">Who Gets the House?</Link></li>
                <li><Link href="/how-pensions-split-divorce-uk" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-how-pensions">How Pensions Are Split</Link></li>
              </ul>
            </div>
            <div>
              <p className="text-xs font-semibold text-white/60 uppercase tracking-wider mb-3">Legal &amp; Support</p>
              <ul className="space-y-2">
                <li><Link href="/methodology" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-methodology">Model Methodology</Link></li>
                <li><Link href="/privacy" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-privacy">Privacy Policy</Link></li>
                <li><Link href="/terms" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-terms">Terms of Use</Link></li>
                <li><Link href="/refund-policy" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-refund-policy">Refund Policy</Link></li>
                <li><Link href="/contact" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-contact">Contact &amp; Support</Link></li>
                <li><Link href="/recover" onClick={scrollTop} className="text-xs text-white/50 hover:text-white transition-colors" data-testid="link-recover">Recover Access</Link></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-white/10 pt-6 space-y-2 text-center">
            <p className="text-xs text-white/35">
              Illustrative financial modelling only. This tool does not provide legal, tax, or financial advice.
            </p>
            <p className="text-xs text-white/25">
              &copy; {new Date().getFullYear()} DivorceCalculatorUK
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
