import { useDocumentTitle } from "@/hooks/use-document-title";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  useDocumentTitle("Terms of Use | DivorceCalculatorUK");
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-3xl">
        <Button
          variant="ghost"
          onClick={() => setLocation("/")}
          className="mb-6"
          data-testid="button-back-home"
        >
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
        </Button>

        <h1 className="text-3xl font-display font-bold mb-8" data-testid="text-terms-title">Terms of Use</h1>

        <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground">
          <p className="text-foreground font-medium">Last updated: February 2026</p>

          <section>
            <h2 className="text-xl font-semibold text-foreground">1. About This Service</h2>
            <p>DivorceCalculatorUK is a financial modelling tool that provides illustrative, scenario-based financial analysis for individuals navigating separation and divorce. The tool generates projections based on data you provide and assumptions you configure.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">2. Important Disclaimer</h2>
            <p className="font-medium text-foreground">This tool does not provide legal advice, tax advice, or regulated financial advice. The outputs are illustrative models only and should not be relied upon as the basis for any legal, financial, or tax decision.</p>
            <p>You should always seek independent professional advice from a qualified solicitor, financial adviser, or tax professional before making decisions related to divorce financial settlements.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">3. Accuracy of Information</h2>
            <p>All modelling outputs are estimates produced by a simplified mathematical model. We make no warranty — express or implied — regarding the accuracy, completeness, reliability, or fitness for purpose of any calculations, projections, or outputs generated by this tool.</p>
            <p>Outputs may contain errors, omissions, or inaccuracies regardless of the accuracy or completeness of the data you provide. The model applies simplifying assumptions, uses generalised parameters, and does not account for the full complexity of individual financial, tax, or legal circumstances. Users must not treat any output as a definitive or reliable statement of their financial position.</p>
            <p className="font-medium mt-2">Tax model scope:</p>
            <p>The tax engine applies a simplified UK income tax and employee Class 1 National Insurance calculation only, based on published HMRC rates for the 2025/26 tax year. Personal allowance tapering above £100,000 is modelled. The following are explicitly excluded from the tax model:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Dividend tax rates (8.75% / 33.75% / 39.35%) and the £1,000 dividend allowance — all income is taxed at standard income tax rates</li>
              <li>Savings income allowance and starting rate for savings</li>
              <li>Capital Gains Tax on disposal of any assets</li>
              <li>Scottish income tax rates — England, Wales, and Northern Ireland rates are applied to all parties regardless of residence</li>
              <li>Self-employed National Insurance contributions (Class 2 and Class 4) — employee Class 1 rates are applied to all income sources</li>
              <li>High Income Child Benefit Charge (income above £60,000)</li>
              <li>Pension contribution tax relief (salary sacrifice or relief at source)</li>
              <li>Student loan repayments (Plan 1, Plan 2, Plan 4, or Postgraduate)</li>
              <li>Marriage Allowance and Married Couple's Allowance</li>
              <li>Any other tax reliefs, allowances, or exemptions not explicitly listed</li>
            </ul>
            <p>Published HMRC rates may be subject to change. Tax rates, thresholds, and allowances applicable at the time of use may differ from those modelled. All tax outputs should be independently verified by a qualified tax adviser.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">4. Access and Payment</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>A limited preview of results is available free of charge.</li>
              <li>Full access to the structured financial analysis requires a one-time payment of £79.</li>
              <li>Full access is valid for 6 months from the date of purchase.</li>
              <li>Access is linked to your browser session. Clearing browser data may affect access.</li>
              <li>Payments are processed by Stripe and are non-refundable except where required by consumer protection law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">5. Consumer Rights</h2>
            <p>Under the Consumer Rights Act 2015 and the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>You have a 14-day cooling-off period from the date of purchase.</li>
              <li>If you access the full analysis within the cooling-off period, you acknowledge that you have requested immediate performance and that you may lose your right to cancel.</li>
              <li>If the service does not meet reasonable expectations, you may be entitled to a remedy under consumer protection law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">6. No Advisory Relationship</h2>
            <p>Use of this tool does not create any professional-client, advisory, fiduciary, or other similar relationship between you and DivorceCalculatorUK, its operators, or any affiliated party. No duty of care arises from your use of this tool.</p>
            <p>The tool does not assess the suitability, fairness, or appropriateness of any financial settlement. It does not predict court outcomes, assess legal entitlement, or provide mortgage eligibility assessments.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">7. No Reliance</h2>
            <p>You acknowledge and agree that you will not rely on the outputs of this tool as the basis for any legal, financial, or tax decision. All outputs are generated solely from the assumptions and data you provide, and may contain errors, omissions, or inaccuracies.</p>
            <p>Mortgage affordability indicators are based on generalised market benchmarks and do not constitute a lending assessment, mortgage offer, or credit evaluation. They should not be interpreted as an indication that any mortgage application would be approved.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">8. User Responsibility for Data Input</h2>
            <p>The accuracy and completeness of all modelling outputs depends entirely on the data you enter. You are solely responsible for ensuring that the information you provide is accurate, complete, and up to date.</p>
            <p>DivorceCalculatorUK does not verify, validate, or audit the data you enter. Incomplete or inaccurate inputs will produce incomplete or inaccurate outputs.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">9. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, we shall not be liable for any loss, damage, or expense arising from your use of, or reliance on, the modelling outputs produced by this tool. This includes but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Financial loss, including losses arising from settlement decisions</li>
              <li>Legal costs or expenses</li>
              <li>Any indirect, consequential, or incidental damages</li>
              <li>Losses arising from errors in user-provided data</li>
              <li>Losses arising from changes in tax rates, legislation, or personal circumstances after the date of use</li>
            </ul>
            <p>Our total liability for any claim shall not exceed the amount paid by you for access to the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">10. Intellectual Property</h2>
            <p>All content, design, and functionality of DivorceCalculatorUK is protected by copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works without written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">11. Governing Law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">12. Changes to These Terms</h2>
            <p>We reserve the right to update these terms at any time. Changes will be posted on this page with an updated revision date. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
