import { useDocumentTitle } from "@/hooks/use-document-title";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  useDocumentTitle("Terms of Use | DivorceCalculatorUK");
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-3xl">
        <Button
          variant="ghost"
          onClick={() => setLocation("/")}
          className="mb-6"
          data-testid="button-back-home"
        >
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
        </Button>

        <h1 className="text-3xl font-display font-bold mb-8" data-testid="text-terms-title">Terms of Use</h1>

        <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground">
          <p className="text-foreground font-medium">Last updated: February 2026</p>

          <section>
            <h2 className="text-xl font-semibold text-foreground">1. About This Service</h2>
            <p>DivorceCalculatorUK is a financial modelling tool that provides illustrative, scenario-based financial analysis for individuals navigating separation and divorce. The tool generates projections based on data you provide and assumptions you configure.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">2. Important Disclaimer</h2>
            <p className="font-medium text-foreground">This tool does not provide legal advice, tax advice, or regulated financial advice. The outputs are illustrative models only and should not be relied upon as the basis for any legal, financial, or tax decision.</p>
            <p>You should always seek independent professional advice from a qualified solicitor, financial adviser, or tax professional before making decisions related to divorce financial settlements.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">3. Accuracy of Information</h2>
            <p>The accuracy of the modelling outputs depends entirely on the accuracy and completeness of the data you provide. We make no warranty regarding the accuracy, completeness, or reliability of any calculations or projections generated by the tool.</p>
            <p>Tax calculations are based on published UK HMRC rates for the 2025/26 tax year. These may be subject to change and should be verified independently.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">4. Access and Payment</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>A limited preview of results is available free of charge.</li>
              <li>Full access to the structured financial analysis requires a one-time payment of £79.</li>
              <li>Full access is valid for 6 months from the date of purchase.</li>
              <li>Access is linked to your browser session. Clearing browser data may affect access.</li>
              <li>Payments are processed by Stripe and are non-refundable except where required by consumer protection law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">5. Consumer Rights</h2>
            <p>Under the Consumer Rights Act 2015 and the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>You have a 14-day cooling-off period from the date of purchase.</li>
              <li>If you access the full analysis within the cooling-off period, you acknowledge that you have requested immediate performance and that you may lose your right to cancel.</li>
              <li>If the service does not meet reasonable expectations, you may be entitled to a remedy under consumer protection law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">6. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, we shall not be liable for any loss, damage, or expense arising from your use of, or reliance on, the modelling outputs produced by this tool. This includes but is not limited to financial loss, legal costs, or any indirect or consequential damages.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">7. Intellectual Property</h2>
            <p>All content, design, and functionality of DivorceCalculatorUK is protected by copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works without written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">8. Governing Law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">9. Changes to These Terms</h2>
            <p>We reserve the right to update these terms at any time. Changes will be posted on this page with an updated revision date. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
